
# ngrok_setup.py
import subprocess
import time

# Replace 'YOUR_AUTH_TOKEN' with your actual ngrok authentication token
auth_token = '2RSErRz0xqml3ILveVIlkNS1ksS_5xTrkHHbhF2Rrz1qH2qTY'

# Start ngrok in a separate process
ngrok_process = subprocess.Popen(['ngrok', 'http', '8000', '--authtoken', auth_token])

# Allow some time for ngrok to initialize (adjust as needed)
time.sleep(2)

# Get the public URL generated by ngrok
ngrok_info = subprocess.run(['ngrok', 'http', '8000', '--authtoken', auth_token], capture_output=True, text=True)
public_url = ngrok_info.stdout.splitlines()[1].split()[-1]

print(f'Public URL: {public_url}')

# Optionally, you can wait for the ngrok process to complete when your script exits
ngrok_process.wait()
